name: CI

on:
  [push, pull_request, workflow_dispatch]

jobs:
  linting-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Run checks with tox
      run: tox -v
      env:
        TOXENV: check

  docs-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install pandoc
      run: sudo apt-get install pandoc
    - name: Build docs with tox
      run: tox -v
      env:
        TOXENV: docs

  unittests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - python-version: 3.6
            toxenv: "py36-cover"
          - python-version: 3.7
            toxenv: "py37-cover"
          - python-version: 3.8
            toxenv: "py38-cover"

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip --version
        virtualenv --version
        tox --version

    - name: Test with tox
      run: tox -v
      env:
        TOXENV: ${{ matrix.toxenv }}
